development:
    adapter: mysql2
    socket: /var/run/mysqld/mysqld.sock
    database: rails
    username: rails
    password: lowMIBPPji
    host: localhost


production:
    adapter: mysql2
    socket: /var/run/mysqld/mysqld.sock
    database: rails
    username: rails
    password: lowMIBPPji
    host: localhost